_default:
  @ just --list --unsorted

# ------------------------- Deployment via CLI -------------------------

# Init (fetch dependencies and state)
init:
  #!/bin/sh
  set -eu
  export AWS_PROFILE=managed_prototypes
  terraform init

# Init + upgrade state
init-upgrade:
  #!/bin/sh
  set -eu
  export AWS_PROFILE=managed_prototypes
  terraform init -upgrade

# Plan (dry run)
plan:
  #!/bin/sh
  set -eu
  export AWS_PROFILE=managed_prototypes
  terraform plan \
    -var-file="local.tfvars"

# Apply (deploy)
apply:
  #!/bin/sh
  set -eu
  export AWS_PROFILE=managed_prototypes
  terraform apply \
    -auto-approve \
    -var-file="local.tfvars"

# Destroy
destroy:
  #!/bin/sh
  set -eu
  export AWS_PROFILE=managed_prototypes
  terraform destroy \
    -auto-approve \
    -var-file="local.tfvars"

# Show the current state
show:
  #!/bin/sh
  set -eu
  export AWS_PROFILE=managed_prototypes
  terraform show

# Apply and save cluster configuration (for kubectl)
apply-and-kubectl: 
  #!/bin/sh
  set -eu
  export AWS_PROFILE=managed_prototypes
  terraform apply \
    -auto-approve \
    -var-file="local.tfvars" \
    -var="write_kubeconfig=true"

# Get pods (using the cluster configuration)
check-kubectl: 
  #!/bin/sh
  set -eu
  # export KUBECONFIG=$(terraform output -raw kubeconfig_path) # Note: returns absolute path, but requires AWS_PROFILE
  export KUBECONFIG="./kubernetes-cluster-access.yaml"
  # watch kubectl get pods -n test
  # kubectl get ns
  # kubectl get pods -n web-k8s
  # kubectl get all
  echo "================== namespaces"
  kubectl get ns
  echo "================== services"
  kubectl get services --all-namespaces
  echo "================== pods"
  kubectl get pods --all-namespaces
  echo "================== Certificates"
  kubectl get Certificates --all-namespaces
  echo "================== secrets"
  kubectl get secrets --all-namespaces
  echo "================== traefik service"
  kubectl describe service traefik -n traefik
  # watch kubectl get certificates --all-namespaces
  # kubectl get ingress --all-namespaces

  
